// AUTO-GENERATED SEED DATA — see BRE-3.
// Sourced from the community radio-browser.info directory, then each
// stream URL was independently verified to return live audio bytes
// (audio/* content-type) on 2026-09-01. Regenerate + re-verify if streams rot.
//
// streamUrl is volatile by nature; treat a dead stream as data to refresh,
// not a code bug.

import type { Station } from "./types";

export const STATIONS: Station[] = [
  {
    id: "slam-101-1-haggatt-hall-bb",
    name: "Slam 101.1 - Haggatt Hall",
    country: "Barbados",
    countryCode: "BB",
    city: "Bridgetown",
    genres: ["reggae", "soca"],
    language: "English",
    streamUrl: "https://usa19.fastcast4u.com:4420/;",
    streamFormat: "mp3",
    bitrateKbps: 320,
    website: "http://www.slam101fm.com/",
    description: "Reggae, Soca radio from Bridgetown, Barbados.",
  },
  {
    id: "boom-94fm-tt",
    name: "BOOM 94FM",
    country: "Trinidad & Tobago",
    countryCode: "TT",
    city: "Port of Spain",
    genres: ["soca", "reggae"],
    language: "English",
    streamUrl: "https://s8.yesstreaming.net:17103/stream",
    streamFormat: "mp3",
    bitrateKbps: 320,
    website: "https://boomchampionstt.com/",
    logoUrl: "https://i0.wp.com/boomchampionstt.com/wp-content/uploads/2022/01/cropped-94fav.jpg",
    description: "Soca, Reggae radio from Port of Spain, Trinidad & Tobago.",
  },
  {
    id: "mello-radio-88-fm-jm",
    name: "Mello Radio 88 FM",
    country: "Jamaica",
    countryCode: "JM",
    city: "Kingston",
    genres: ["dancehall", "reggae"],
    language: "English",
    streamUrl: "http://peridot.streamguys.com:5660/live",
    available: false,
    unavailableReason:
      "No HTTPS stream available upstream; the HTTP stream is blocked as mixed content on the HTTPS site (BRE-35). Re-enable when an HTTPS mount is found.",
    streamFormat: "aac",
    bitrateKbps: 64,
    website: "http://www.mellofmjamaica.com/",
    description: "Dancehall, Reggae radio from Kingston, Jamaica.",
  },
  {
    id: "alpha-boys-school-radio-jm",
    name: "Alpha Boys School Radio",
    country: "Jamaica",
    countryCode: "JM",
    city: "Kingston",
    genres: ["reggae", "ska", "jazz"],
    language: "English",
    streamUrl: "https://alphaboys-live.streamguys1.com/alphaboys.mp3",
    streamFormat: "mp3",
    bitrateKbps: 128,
    website: "http://www.alphaboysschoolradio.com/",
    logoUrl: "https://static.wixstatic.com/media/a09246_33fe4aef6e5f4f17b605a8d8645ff015%7emv2.png/v1/fill/w_32%2ch_32%2clg_1%2cusm_0.66_1.00_0.01/a09246_33fe4aef6e5f4f17b605a8d8645ff015%7emv2.png",
    description: "Reggae, Ska, Jazz radio from Kingston, Jamaica.",
  },
  {
    id: "suncity-104-9-fm-jm",
    name: "Suncity 104.9 FM",
    country: "Jamaica",
    countryCode: "JM",
    city: "Kingston",
    genres: ["dancehall", "reggae", "hiphop"],
    language: "English",
    streamUrl: "https://edge.mixlr.com/channel/ibrdq",
    streamFormat: "mp3",
    website: "https://www.suncityradio.fm/",
    logoUrl: "https://radiosjamaica.com/sites/default/files/styles/116_x_116/public/radio/logos/logo-suncity-radio.png",
    description: "Dancehall, Reggae, Hiphop radio from Kingston, Jamaica.",
  },
  {
    id: "radio-tambrin-92-7-scarborough-tt",
    name: "Radio Tambrin 92.7 - Scarborough",
    country: "Trinidad & Tobago",
    countryCode: "TT",
    city: "Scarborough",
    genres: ["talk", "news", "calypso"],
    language: "English",
    streamUrl: "https://ice42.securenetsystems.net/TAMBRIN",
    streamFormat: "aac",
    bitrateKbps: 32,
    website: "http://tambrintobago.com/",
    description: "Talk, News, Calypso radio from Scarborough, Trinidad & Tobago.",
  },
  {
    id: "rebel-radio-jm",
    name: "Rebel Radio",
    country: "Jamaica",
    countryCode: "JM",
    city: "Kingston",
    genres: ["reggae"],
    language: "English",
    streamUrl: "https://streamer.radio.co/s830ce6f36/listen",
    streamFormat: "mp3",
    bitrateKbps: 192,
    website: "https://www.facebook.com/rebelradiolink.co",
    logoUrl: "https://www.facebook.com/favicon.ico",
    description: "Reggae radio from Kingston, Jamaica.",
  },
  {
    id: "scorch-radio-101-1fm-tt",
    name: "Scorch Radio 101.1FM",
    country: "Trinidad & Tobago",
    countryCode: "TT",
    city: "Port of Spain",
    genres: ["soca"],
    language: "English",
    streamUrl: "https://stream.velalabs.co/scorch",
    streamFormat: "mp3",
    bitrateKbps: 128,
    website: "https://www.thescorch.com/",
    description: "Soca radio from Port of Spain, Trinidad & Tobago.",
  },
  {
    id: "isaac-98-1fm-tt",
    name: "Isaac 98.1fm",
    country: "Trinidad & Tobago",
    countryCode: "TT",
    city: "Port of Spain",
    genres: ["gospel"],
    language: "English",
    streamUrl: "https://ice66.securenetsystems.net/FFBN?playSessionID=8D29A2B7-D966-0B14-AFCD7A340AFA6C15",
    streamFormat: "aac",
    bitrateKbps: 32,
    website: "http://www.isaac981.com/",
    description: "Gospel radio from Port of Spain, Trinidad & Tobago.",
  },
  {
    id: "hott-95-3fm-bb",
    name: "HOTT 95.3FM",
    country: "Barbados",
    countryCode: "BB",
    city: "Bridgetown",
    genres: ["reggae"],
    language: "English",
    streamUrl: "https://ice64.securenetsystems.net/HOTT953",
    streamFormat: "aac",
    bitrateKbps: 64,
    website: "https://starcomnetwork.net/radio-stations/stream-hott-95-3-fm",
    logoUrl: "https://starcomnetwork.net/wp-content/uploads/2024/01/HOTT-953-FM-LOGO-full-colour-wide-3-1536x840.png",
    description: "Reggae radio from Bridgetown, Barbados.",
  },
  {
    id: "irie-fm-jm",
    name: "Irie FM",
    country: "Jamaica",
    countryCode: "JM",
    city: "Ocho Rios",
    genres: ["reggae", "talk"],
    language: "English",
    streamUrl: "https://stream.iriefm.net:8008/stream",
    streamFormat: "mp3",
    bitrateKbps: 64,
    website: "https://iriefm.net/",
    logoUrl: "https://iriefm-wp-upload.nyc3.digitaloceanspaces.com/uploads/Logo.png",
    description: "Reggae, Talk radio from Ocho Rios, Jamaica.",
  },
  {
    id: "vob-92-9-fm-bb",
    name: "VOB 92.9 FM",
    country: "Barbados",
    countryCode: "BB",
    city: "Bridgetown",
    genres: ["talk", "news", "soca", "calypso"],
    language: "English",
    streamUrl: "https://ice66.securenetsystems.net:80/VOB929",
    streamFormat: "aac",
    bitrateKbps: 48,
    website: "https://vob929.com/",
    logoUrl: "https://cdn-profiles.tunein.com/s16653/images/logog.png?t=1",
    description: "Talk, News, Soca, Calypso radio from Bridgetown, Barbados.",
  },
  {
    id: "hj94-1-boom-fm-georgetown-gy",
    name: "HJ94.1 Boom FM Georgetown",
    country: "Guyana",
    countryCode: "GY",
    city: "Georgetown",
    genres: ["chutney", "bollywood", "soca"],
    language: "English",
    streamUrl: "http://192.99.8.192:3630/stream",
    available: false,
    unavailableReason:
      "No HTTPS stream available upstream; the HTTP stream is blocked as mixed content on the HTTPS site (BRE-35). Re-enable when an HTTPS mount is found.",
    streamFormat: "mp3",
    bitrateKbps: 192,
    website: "http://www.hj941.com/",
    description: "Chutney, Bollywood, Soca radio from Georgetown, Guyana.",
  },
  {
    id: "big-reggae-mix-ht",
    name: "Big Reggae Mix",
    country: "Haiti",
    countryCode: "HT",
    city: "Port-au-Prince",
    genres: ["reggae"],
    language: "English",
    streamUrl: "https://ais-sa2.cdnstream1.com/2294_128.mp3",
    streamFormat: "mp3",
    bitrateKbps: 128,
    website: "https://www.bigreggaemix.com/",
    description: "Reggae radio from Port-au-Prince, Haiti.",
  },
  {
    id: "life-97-5-fm-bb",
    name: "LIFE 97.5 FM",
    country: "Barbados",
    countryCode: "BB",
    city: "Bridgetown",
    genres: ["gospel"],
    language: "English",
    streamUrl: "https://ice64.securenetsystems.net/LIFE975",
    streamFormat: "aac",
    bitrateKbps: 64,
    website: "https://starcomnetwork.net/radio-stations/stream-life-97-5-fm/",
    logoUrl: "https://starcomnetwork.net/wp-content/uploads/2023/06/Life97.5FM.png",
    description: "Gospel radio from Bridgetown, Barbados.",
  },
  {
    id: "radio-bachata-do",
    name: "Radio Bachata",
    country: "Dominican Republic",
    countryCode: "DO",
    city: "Santo Domingo",
    genres: ["bachata"],
    language: "Spanish",
    streamUrl: "http://perseus.shoutca.st:8312/;stream/1",
    available: false,
    unavailableReason:
      "No HTTPS stream available upstream; the HTTP stream is blocked as mixed content on the HTTPS site (BRE-35). Re-enable when an HTTPS mount is found.",
    streamFormat: "mp3",
    bitrateKbps: 128,
    website: "http://radiobachata.net/",
    logoUrl: "http://radiobachata.net/favicon.ico",
    description: "Bachata radio from Santo Domingo, Dominican Republic.",
  },
  {
    id: "top-salsa-radio-do",
    name: "Top Salsa Radio",
    country: "Dominican Republic",
    countryCode: "DO",
    city: "Santo Domingo",
    genres: ["salsa"],
    language: "Spanish",
    streamUrl: "https://radio.dominiserver.com/proxy/topsalsaradio?mp=/stream",
    streamFormat: "aac",
    bitrateKbps: 128,
    website: "https://latina104.net/top-salsa-radio/",
    logoUrl: "https://latina104.net/wp-content/uploads/2021/06/cropped-latina-104-500x500-1-180x180.jpg",
    description: "Salsa radio from Santo Domingo, Dominican Republic.",
  },
  {
    id: "ntn-radio-89-1-georgetown-gy",
    name: "NTN Radio 89.1 Georgetown",
    country: "Guyana",
    countryCode: "GY",
    city: "Georgetown",
    genres: ["chutney", "bollywood"],
    language: "English",
    streamUrl: "https://auds1.intacs.com/ntnradio",
    streamFormat: "mp3",
    bitrateKbps: 128,
    website: "http://ntntv-radio.com/",
    description: "Chutney, Bollywood radio from Georgetown, Guyana.",
  },
  {
    id: "top-merengue-radio-do",
    name: "Top Merengue Radio",
    country: "Dominican Republic",
    countryCode: "DO",
    city: "Santo Domingo",
    genres: ["merengue"],
    language: "Spanish",
    streamUrl: "https://radio.dominiserver.com/proxy/topmerengueradio?mp=/stream",
    streamFormat: "aac",
    bitrateKbps: 128,
    website: "https://latina104.net/top-merengue-radio/",
    description: "Merengue radio from Santo Domingo, Dominican Republic.",
  },
  {
    id: "la-z101-fm-do",
    name: "La Z101 Fm",
    country: "Dominican Republic",
    countryCode: "DO",
    city: "Santo Domingo",
    genres: ["news", "talk"],
    language: "Spanish",
    streamUrl: "https://streaming.z101digital.com/z101?cb=1779372229211",
    streamFormat: "mp3",
    bitrateKbps: 128,
    website: "https://z101digital.com/",
    description: "News, Talk radio from Santo Domingo, Dominican Republic.",
  },
  {
    id: "men-konpa-ht",
    name: "Men Konpa",
    country: "Haiti",
    countryCode: "HT",
    city: "Port-au-Prince",
    genres: ["kompa"],
    language: "Haitian Creole",
    streamUrl: "https://stream.radio.co/s84b4fb736/listen",
    streamFormat: "mp3",
    bitrateKbps: 192,
    website: "http://www.menkonpa.com/",
    description: "Kompa radio from Port-au-Prince, Haiti.",
  },
  {
    id: "caribbean-hot-fm-105-3-castries-lc",
    name: "Caribbean Hot FM 105.3 - Castries",
    country: "Saint Lucia",
    countryCode: "LC",
    city: "Castries",
    genres: ["variety", "soca"],
    language: "English",
    streamUrl: "https://auds2.intacs.com/caribbeanhotfm",
    streamFormat: "mp3",
    bitrateKbps: 128,
    website: "http://www.caribbeanhotfm.com/",
    description: "Variety, Soca radio from Castries, Saint Lucia.",
  },
  {
    id: "reggae141-vc",
    name: "Reggae141",
    country: "Saint Vincent & the Grenadines",
    countryCode: "VC",
    city: "Kingstown",
    genres: ["reggae"],
    language: "English",
    streamUrl: "https://hestia2.cdnstream.com/1301_128",
    streamFormat: "mp3",
    bitrateKbps: 128,
    website: "http://www.reggae141.com/",
    logoUrl: "http://www.reggae141.com/favicon.ico",
    description: "Reggae radio from Kingstown, Saint Vincent & the Grenadines.",
  },
  {
    id: "102-5-fm-voice-of-guyana-gy",
    name: "102.5 FM Voice of Guyana",
    country: "Guyana",
    countryCode: "GY",
    city: "Georgetown",
    genres: ["talk", "news", "variety"],
    language: "English",
    streamUrl: "https://cast4.asurahosting.com/proxy/ncn1025/stream",
    streamFormat: "mp3",
    bitrateKbps: 128,
    website: "https://ncnguyana.com/2023/vogradio/",
    logoUrl: "https://ncnguyana.com/2023/wp-content/uploads/2023/08/vog-155x155.png",
    description: "Talk, News, Variety radio from Georgetown, Guyana.",
  },
  {
    id: "intermix-93-1-fm-ht",
    name: "Intermix 93.1 FM",
    country: "Haiti",
    countryCode: "HT",
    city: "Port-au-Prince",
    genres: ["kompa", "variety"],
    language: "Haitian Creole",
    streamUrl: "https://studio.sitegenial.com/9310/stream",
    streamFormat: "aac",
    bitrateKbps: 64,
    website: "https://www.radiointermix.com/",
    logoUrl: "https://www.radiointermix.com/logo.png",
    description: "Kompa, Variety radio from Port-au-Prince, Haiti.",
  },
  {
    id: "radio-scoop-fm-ht",
    name: "Radio Scoop FM",
    country: "Haiti",
    countryCode: "HT",
    city: "Port-au-Prince",
    genres: ["talk", "news"],
    language: "Haitian Creole",
    streamUrl: "https://studio.sitegenial.com/8006/stream",
    streamFormat: "aac",
    bitrateKbps: 64,
    website: "https://www.scoopfmhaiti.com/",
    description: "Talk, News radio from Port-au-Prince, Haiti.",
  },
  {
    id: "96-9-fm-guardianradio-bs",
    name: "96.9 FM GuardianRadio",
    country: "Bahamas",
    countryCode: "BS",
    city: "Nassau",
    genres: ["talk", "news", "variety"],
    language: "English",
    streamUrl: "https://radiostreams.streamcomedia.com:8000/969guardianradio",
    streamFormat: "mp3",
    bitrateKbps: 96,
    website: "https://guardiantalkradio.com/",
    logoUrl: "https://guardiantalkradio.com/wp-content/themes/guardianradio/images/logo_site1.png",
    description: "Talk, News, Variety radio from Nassau, Bahamas.",
  },
  {
    id: "bahamian-or-nuttin-bs",
    name: "Bahamian or Nuttin",
    country: "Bahamas",
    countryCode: "BS",
    city: "Nassau",
    genres: ["junkanoo", "variety"],
    language: "English",
    streamUrl: "https://s2.reliastream.com/proxy/rumcayme?mp=/stream",
    streamFormat: "mp3",
    bitrateKbps: 128,
    website: "https://www.bahamianornuttin.com/",
    logoUrl: "https://img1.wsimg.com/isteam/ip/3828e59f-f1ce-4e2a-8946-b8dbdfaadc31/favicon/78d0b8fe-c6cf-4ef3-a4dc-f5284754eed2.png/:/rs=w:64,h:64,m",
    description: "Junkanoo, Variety radio from Nassau, Bahamas.",
  },
  {
    id: "nbc-radio-svg-vc",
    name: "NBC Radio SVG",
    country: "Saint Vincent & the Grenadines",
    countryCode: "VC",
    city: "Kingstown",
    genres: ["calypso", "soca", "talk"],
    language: "English",
    streamUrl: "https://us1.carihost.com:2020/stream/NBCSVG/",
    streamFormat: "mp3",
    bitrateKbps: 128,
    website: "https://www.nbcsvg.com/",
    logoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSH-MhcovxDQuheSaQ4gAGlgfJd3PFHVbjez1Wlm28BhVAEpMMixgckaP4&s=10",
    description: "Calypso, Soca, Talk radio from Kingstown, Saint Vincent & the Grenadines.",
  },
  {
    id: "hot-97-fm-vc",
    name: "Hot 97 FM",
    country: "Saint Vincent & the Grenadines",
    countryCode: "VC",
    city: "Kingstown",
    genres: ["pop", "soca"],
    language: "English",
    streamUrl: "https://usa7.fastcast4u.com/proxy/hot97svg?mp=/1",
    streamFormat: "mp3",
    bitrateKbps: 320,
    website: "https://tunein.com/radio/Hot-97-FM-971-s89438/",
    logoUrl: "https://cdn-profiles.tunein.com/s89438/images/logod.png?t=637197376260000000",
    description: "Pop, Soca radio from Kingstown, Saint Vincent & the Grenadines.",
  },
  {
    id: "flava-fm-100-7-ag",
    name: "Flava FM 100.7",
    country: "Antigua & Barbuda",
    countryCode: "AG",
    city: "St. John's",
    genres: ["variety", "soca"],
    language: "English",
    streamUrl: "http://167.114.11.80:5322/stream/;",
    available: false,
    unavailableReason:
      "No HTTPS stream available upstream; the HTTP stream is blocked as mixed content on the HTTPS site (BRE-35). Re-enable when an HTTPS mount is found.",
    streamFormat: "aac",
    bitrateKbps: 128,
    website: "https://www.flavafm268.com/",
    logoUrl: "https://static.wixstatic.com/media/fef281_95a788d2549b4134957a9efc21a5dcac~mv2.png/v1/fill/w_523,h_423,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/FLAVA_LOGO_FREQ.png",
    description: "Variety, Soca radio from St. John's, Antigua & Barbuda.",
  },
  {
    id: "rev-up-slu-lc",
    name: "REV-UP SLU",
    country: "Saint Lucia",
    countryCode: "LC",
    city: "Castries",
    genres: ["reggae", "soca", "zouk"],
    language: "English",
    streamUrl: "https://caribspy.com/proxy/revupslu/stream",
    streamFormat: "mp3",
    bitrateKbps: 128,
    website: "https://revupslu.com/",
    description: "Reggae, Soca, Zouk radio from Castries, Saint Lucia.",
  },
  {
    id: "antigua-observer-radio-91-1-st-john-s-ag",
    name: "Antigua Observer Radio 91.1 St. John's",
    country: "Antigua & Barbuda",
    countryCode: "AG",
    city: "St. John's",
    genres: ["talk", "news"],
    language: "English",
    streamUrl: "http://s8.voscast.com:8176/;",
    available: false,
    unavailableReason:
      "No HTTPS stream available upstream; the HTTP stream is blocked as mixed content on the HTTPS site (BRE-35). Re-enable when an HTTPS mount is found.",
    streamFormat: "mp3",
    bitrateKbps: 192,
    website: "http://antiguaobserver.com/",
    description: "Talk, News radio from St. John's, Antigua & Barbuda.",
  },
  {
    id: "wee-fm-93-3-93-9-grenada-gd",
    name: "Wee FM 93.3/93.9 - Grenada",
    country: "Grenada",
    countryCode: "GD",
    city: "St. George's",
    genres: ["reggae", "soca", "talk"],
    language: "English",
    streamUrl: "https://usa8.fastcast4u.com/proxy/weefm2?mp=/1",
    streamFormat: "mp3",
    bitrateKbps: 128,
    website: "https://www.weefmgrenada.com/",
    description: "Reggae, Soca, Talk radio from St. George's, Grenada.",
  },
  {
    id: "radio-shruti-sr",
    name: "Radio Shruti",
    country: "Suriname",
    countryCode: "SR",
    city: "Paramaribo",
    genres: ["chutney", "bollywood"],
    language: "Sarnami/Hindi",
    streamUrl: "https://rs.suricloud.com/radio/8000/radio.mp3",
    streamFormat: "mp3",
    bitrateKbps: 192,
    website: "https://rs.suricloud.com/radio/8000/radio.mp3",
    description: "Chutney, Bollywood radio from Paramaribo, Suriname.",
  },
  {
    id: "star-fm-101-9-gd",
    name: "Star FM 101.9",
    country: "Grenada",
    countryCode: "GD",
    city: "St. George's",
    genres: ["reggae", "soca"],
    language: "English",
    streamUrl: "https://starchild.radioca.st/",
    streamFormat: "mp3",
    bitrateKbps: 128,
    website: "https://www.starfmgrenada.com/",
    logoUrl: "https://www.starfmgrenada.com/apple-icon-120x120.png",
    description: "Reggae, Soca radio from St. George's, Grenada.",
  },
  {
    id: "radio-apintie-sr",
    name: "Radio Apintie",
    country: "Suriname",
    countryCode: "SR",
    city: "Paramaribo",
    genres: ["variety"],
    language: "Dutch",
    streamUrl: "https://surilive.com:8000/str",
    streamFormat: "aac",
    bitrateKbps: 64,
    website: "https://www.apintie.sr/radio",
    description: "Variety radio from Paramaribo, Suriname.",
  },
  {
    id: "dbs-radio-dm",
    name: "DBS Radio",
    country: "Dominica",
    countryCode: "DM",
    city: "Roseau",
    genres: ["talk", "news", "variety"],
    language: "English",
    streamUrl: "https://stream.dbcradio.net:8005/live",
    streamFormat: "mp3",
    bitrateKbps: 96,
    website: "https://dbcradio.net/",
    logoUrl: "https://dbcradio.net/wp-content/uploads/2024/01/dbs_web_logo_dark.png",
    description: "Talk, News, Variety radio from Roseau, Dominica.",
  },
  {
    id: "en-ba-mango-dm",
    name: "En Ba Mango",
    country: "Dominica",
    countryCode: "DM",
    city: "Roseau",
    genres: ["zouk", "kompa"],
    language: "French/Creole",
    streamUrl: "https://s10.myradiostream.com/:4212/listen.mp3",
    streamFormat: "mp3",
    bitrateKbps: 128,
    website: "https://www.facebook.com/oobinmmani/",
    description: "Zouk, Kompa radio from Roseau, Dominica.",
  },
  {
    id: "sugar-city-90-3-fm-kn",
    name: "Sugar City 90.3 FM",
    country: "Saint Kitts & Nevis",
    countryCode: "KN",
    city: "Basseterre",
    genres: ["variety", "soca"],
    language: "English",
    streamUrl: "http://104.131.13.48:8000/radio.mp3",
    available: false,
    unavailableReason:
      "No HTTPS stream available upstream; the HTTP stream is blocked as mixed content on the HTTPS site (BRE-35). Re-enable when an HTTPS mount is found.",
    streamFormat: "mp3",
    bitrateKbps: 128,
    website: "http://www.sugarcityfm.com/wp-content/uploads/2012/06/logo2.png",
    description: "Variety, Soca radio from Basseterre, Saint Kitts & Nevis.",
  },
  {
    id: "krem-radio-bz",
    name: "Krem Radio",
    country: "Belize",
    countryCode: "BZ",
    city: "Belize City",
    genres: ["variety", "talk"],
    language: "English",
    streamUrl: "http://159.65.32.199:8016/;",
    available: false,
    unavailableReason:
      "No HTTPS stream available upstream; the HTTP stream is blocked as mixed content on the HTTPS site (BRE-35). Re-enable when an HTTPS mount is found.",
    streamFormat: "mp3",
    bitrateKbps: 128,
    website: "http://www.krembz.com/",
    logoUrl: "https://i0.wp.com/www.krembz.com/wp-content/uploads/2023/04/cropped-favicon.png?fit=180%2c180&#038;ssl=1",
    description: "Variety, Talk radio from Belize City, Belize.",
  },
];
